### ISSUE TITLE
The custom mobs cant spawn naturally !?

### ISSUE THREAD

**Issue by HeiHei1115** [Steel-Dev/Monstrorvm#3] opened 2021-07-23 11:01 UTC
I can see the console have custom Mob spawned , but when I tp or walk through there , I cant see the mob . Anyone know why ?

**Comment by Steel-Dev** [comment] 2021-07-23 20:45
Strange, is there any errors in console?
I'll look into this, thank you for reporting it, I'll update you on what's going on. (most likely a mistake made by me haha)

**Comment by Steel-Dev** [comment] 2021-07-23 21:11
Update: Definitely a bug, working on a fix right now.

**Comment by HeiHei1115** [comment] 2021-07-24 10:35
Thank you

**Comment by Steel-Dev** [comment] 2021-07-24 21:04
Sorry for the delay, had a power outage moments after my last comment, was unable to do much work, sadly.
But, I've resolved the issue. I'll be posting a hotfix on spigot soon, keep watch!

**Comment by Steel-Dev** [comment] 2021-07-24 21:46
Alright, before I post the hotfix on spigot, I'd like you to test out and see if the issue is fixed with this new build.
On my end, it's fine.
You can get it [here](https://drive.google.com/file/d/1qa24BcwQj7kDx--qjX98WPk3mmn1b1d-/view?usp=sharing).
Let me know if there are any issues.
(Also, a new feature in there - right click a spawner with a custom mobs spawn egg while in creative to make the spawner.. well.. spawn that custom mob)

**Closed** 2021-07-25 00:03 UTC

**Comment by HeiHei1115** [comment] 2021-07-25 03:51
how to create custom spawn egg ?

**Comment by Steel-Dev** [comment] 2021-07-25 03:53
When creating a custom mob, add `WithSpawnEgg: NUMBER` (the number being the custom model data for a custom texture - just put 0 if you don't care about that aspect)
and then Monstrorvm will automatically register a spawn egg item for you.
